################################################################
# use bkch to run the cleanup - add another CMD
# it can try to run buildctl prune, if it fails kill the pvc and restart the pod
################################################################
{{- $sa := .Values.argo.service_account.name -}}
{{- if and .Values.argo.enabled .Values.argo.service_account.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $sa }}
## configure rbac ##############################################
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $sa }}
rules:
- apiGroups: ['']
  resources:
    - pods
  verbs:
    - delete
- apiGroups: ['']
  resources:
    - persistentvolumeclaims
  verbs:
    - list
    - delete
- apiGroups:
    - argoproj.io
  resources:
    - workflowtaskresults
  verbs:
    - create
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $sa }}
subjects:
- kind: ServiceAccount
  name: {{ $sa }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ $sa }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
################################################################
