apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "selector_labels" . | nindent 6 }}
  name: {{ .Values.driver.name }}
spec:
  replicas: {{ .Values.driver.replicas }}
  selector:
    matchLabels:
      {{- include "selector_labels" . | nindent 8 }}
  template:
    metadata:
      labels:
      {{- include "selector_labels" . | nindent 8 }}
    spec:
      containers:
      - image: {{ .Values.driver.image.repository }}:{{ .Values.driver.image.tag }}
        imagePullPolicy: IfNotPresent
        name: main
        readinessProbe:
          exec:
            command:
            - buildctl
            - debug
            - workers
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/buildkit
          name: data
        - mountPath: /etc/buildkit
          name: config
      securityContext: {}
      volumes:
      - name: config
        configMap:
          name: {{ .Values.driver.name }}
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.driver.name }}
