apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.driver.name }}
  labels:
    {{- include "selector_labels" . | nindent 6 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.driver.pvc.storage }}
