{{- $root := . -}}
{{- if .Values.bkch.enabled -}}
{{ $service := printf "%s-bkch" .Release.Name }}
{{ if .Values.driver.api_gateway.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ $service }}
spec:
  parentRefs:
    - name: {{ .Values.bkch.api_gateway.parent_gateway.name }}
      namespace: {{ .Values.bkch.api_gateway.parent_gateway.namespace }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ $service }}
          port: {{ .Values.bkch.port }}
  hostnames:
    - {{ .Values.bkch.api_gateway.hostname }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $service }}
  labels:
    app: {{ .Release.Name }}-bkch
spec:
  selector:
    app: {{ .Release.Name }}-bkch
  ports:
    - port: {{ .Values.bkch.port }}
      protocol: TCP
{{- end -}}
