{{- if .Values.bkch.enabled -}}
{{- $driver_name := .Release.Name }}
{{- $sa := printf "%s-bkch" $driver_name }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $sa }}
  labels:
    app: {{ $sa }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $sa }}
rules:
- apiGroups: ['']
  resources: 
    - pods
  verbs: 
    - get
    - list
    - watch
- apiGroups: 
    - apps
  resources: 
    - statefulsets
  verbs: 
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $sa }}
subjects:
- kind: ServiceAccount
  name: {{ $sa }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ $sa }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
