{{- $driver_name := .Release.Name }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels: {{- include "selector_labels" . | nindent 4 }}
  name: {{ $driver_name }}
spec:
  serviceName: {{ $driver_name }}
  podManagementPolicy: Parallel
  replicas: {{ .Values.driver.replicas }}
  selector:
    matchLabels: {{- include "selector_labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "selector_labels" . | nindent 8 }}
      annotations:
        bkch.service-discovery.api-gateway: {{ include "dns.api_gateway" . | quote }}
        bkch.service-discovery.in-cluster: {{ include "dns.in_cluster" . | quote }}
    spec:
      containers:
        - name: main
          imagePullPolicy: {{ .Values.driver.image.pull_policy }}
          image: {{ .Values.driver.image.repository }}:{{ .Values.driver.image.tag }}
          args: {{- range .Values.driver.args }}
            - {{ tpl . $ }}
          {{- end }}
          readinessProbe: {{- toYaml .Values.driver.readinessProbe | nindent 12 }}
          livenessProbe: {{- toYaml .Values.driver.livenessProbe | nindent 12 }}
          securityContext: {{- toYaml .Values.driver.securityContext | nindent 12 }}
          volumeMounts:
            - mountPath: /var/lib/buildkit
              name: data
            - mountPath: /etc/buildkit
              name: config
            {{- if .Values.driver.extraVolumeMounts }}
              {{- tpl .Values.driver.extraVolumeMounts . | nindent 12 }}
            {{- end }}
          {{- if .Values.driver.envFrom }}
          envFrom: {{- tpl .Values.driver.envFrom . | nindent 12 }}
          {{- end }}
          {{- if .Values.driver.env }}
          env: {{- tpl .Values.driver.env . | nindent 12 }}
          {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ $driver_name }}
      {{- if .Values.driver.extraVolumes }}
      {{- tpl .Values.driver.extraVolumes . | nindent 6 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec: {{- toYaml .Values.driver.volumeClaimTemplate | nindent 10 }}

